mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=7islas
    - MYSQL_PASSWORD=7islas
    - MYSQL_DATABASE=7islas
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
